[pytest]
pythonpath = .
asyncio_mode = auto
python_files = test_*.py *_test.py check_*.py
addopts = --import-mode=importlib -p no:cacheprovider
filterwarnings = ignore::DeprecationWarning
asyncio_default_test_loop_scope = function