name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [34]
        target: [google_apis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Restore .env.test file
        run: |
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 -d > .env.test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download APK from Google Drive
        env:
          FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
        run: |
          gdown https://drive.google.com/uc?id=${FILE_ID} -O app-debug.apk
          file app-debug.apk
          unzip -t app-debug.apk || true

      - name: Setup Node.js and Appium
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install -g appium@next
          appium driver install uiautomator2
          npm install -g appium-chromedriver

      - name: Generate AVD snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          # ram-size: 2048M
          # disk-size: 4096M
          # profile: pixel_5
          # avd-name: test-emulator
          # disable-animations: true
          force-avd-creation: false
          emulator-options: -no-snapshot-load -no-snapshot-save -no-boot-anim -no-audio -memory 4096 -port 5554 -wipe-data -feature -Vulkan -gpu host -accel on -no-metrics -writable-system -verbose -skin 440x960 -gpu swiftshader_indirect -feature BluetoothEmulation=off -no-window
          emulator-boot-timeout: 300
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android emulator and Appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          # ram-size: 2048M
          # disk-size: 4096M
          # profile: pixel_5
          # avd-name: test-emulator
          # disable-animations: true
          force-avd-creation: false
          emulator-options: -no-snapshot-load -no-snapshot-save -no-boot-anim -no-audio -memory 4096 -port 5554 -wipe-data -feature -Vulkan -gpu host -accel on -no-metrics -writable-system -verbose -skin 440x960 -gpu swiftshader_indirect -feature BluetoothEmulation=off -no-window
          emulator-boot-timeout: 300
          script: ./e2e_tests.sh