name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Restore .env file
        run: |
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 -d > .env

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download APK from Google Drive
        env:
          FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
        run: |
          gdown https://drive.google.com/uc?id=${FILE_ID} -O app-debug.apk
          file app-debug.apk
          unzip -t app-debug.apk || true

      - name: Setup Node.js and Appium
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install -g appium@next
          appium driver install uiautomator2
          npm install -g appium-chromedriver
          appium --version

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          target: google_apis
          force-avd-creation: true
          emulator-options: "-no-window -no-audio -no-snapshot -gpu swiftshader_indirect -no-boot-anim"
          wait-for-boot: true
          timeout: 360

      - name: Wait for emulator manually
        run: |
          echo "Waiting for emulator to fully boot..."
          adb wait-for-device
          until adb -s emulator-5554 shell getprop sys.boot_completed | grep 1; do
            echo "Emulator still booting..."
            sleep 5
          done
          echo "Emulator is ready!"